Product: 9DXL
BCU:
    port: com5
    baudrate: 115200
COM:
    CM4: com22
    CM4_baudrate: 115200
    uBoot: com23
    uBoot_baudrate: 115200
    SCFW: com24
    SCFW_baudrate: 115200
SD:
    instance:
    secondary_addr:
Image:
    serial_download: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_uboot.bin
    sd_cm4_ddr_uboot: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_sd_scfw_cm4_ddr_uboot.bin
    sd_cm4_ddr_uboot_dummy_ocram: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_sd_scfw_cm4_ddr_uboot_dummy_ocram.bin
    sd_cm4_tcm_uboot_dummy_ddr: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_sd_scfw_cm4_tcm_uboot_dummy_ddr.bin
    emmc_cm4_ddr_uboot: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_emmc_scfw_cm4_ddr_uboot.bin
    emmc_cm4_ddr_uboot_dummy_ocram: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_emmc_scfw_cm4_ddr_uboot_dummy_ocram.bin
    emmc_cm4_tcm_uboot_dummy_ddr: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_emmc_scfw_cm4_tcm_uboot_dummy_ddr.bin
    flexspi_cm4_flexspi: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_flexspi_scfw_cm4_flexspi.bin
    flexspi_cm4_flexspi_uboot: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_flexspi_scfw_cm4_flexspi_uboot.bin
    flexspi_cm4_flexspi_uboot_dummy_ocram: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_flexspi_scfw_cm4_flexspi_uboot_dummy_ocram.bin
    flexspi_cm4_flexspi_uboot_dummy_ddr: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_flexspi_scfw_cm4_flexspi_uboot_dummy_ddr.bin

UUU:
    path: C:\Users\nxa28190\Desktop\8DXL_Auto\tool\uuu.exe






