COM:
    CM4: com26
    CM4_baudrate: 115200
    uBoot: com27
    uBoot_baudrate: 115200
    SCFW: com28
    SCFW_baudrate: 115200

SD:
    instance:
    secondary_addr:

Image:
    serial_download: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_uboot.bin
    cm4_ddr: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_cm4_ddr.bin
    cm4_tcm: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_cm4_ram.bin
    scfw_skip_ddr: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_skip_ddr.bin
    scfw_uboot_dummy_ddr: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_uboot_dummy_ddr.bin
    scfw_uboot_dummy_ocram: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_uboot_dummy_ocram.bin
    cm4_flexspi_uboot: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_cm4_flexspi_uboot.bin
    invalid_scfw_entity: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_cm4_ddr_invalid_scfw_entity.bin
    invalid_scfw_container: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_cm4_ddr_invalid_scfw_container_tag.bin
    invalid_seco_container: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_cm4_ddr_invalid_seco_container_tag.bin
    invalid_seco_fw_entity: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_cm4_ddr_invalid_seco_fw_entity.bin
    scfw_uboot_container_higher_version: D:\Git_repo\rom_validation\8DXL_Auto\image\unsigned_scfw_uboot_scfw_container_version_higher.bin

    flexspi_cm4_flexspi_uboot: D:\Git_repo\rom_validation\8DXL_Auto\image\flexspi_signed_384_scfw_cm4_flexspi_uboot_dummy_ddr_flexspi.bin
    flexspi_invalid_scfw_entity: D:\Git_repo\rom_validation\8DXL_Auto\image\flexspi_unsigned_scfw_cm4_ddr_invalid_scfw_container_tag.bin


UUU:
    path: C:\Users\nxa28190\Desktop\8DXL_Auto\tool\uuu.exe






